// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD73pkR3zrhVs5FlFhkVq-MdZyei-CBoG4',
    appId: '1:975477626776:android:4c7093b60e33efb0d5bded',
    messagingSenderId: '975477626776',
    projectId: 'budgetdev-4662b',
    storageBucket: 'budgetdev-4662b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJ_VhU3QZJhbOJ5h857hZECytyArgm4k',
    appId: '1:975477626776:ios:9a922b5658e69234d5bded',
    messagingSenderId: '975477626776',
    projectId: 'budgetdev-4662b',
    storageBucket: 'budgetdev-4662b.firebasestorage.app',
    androidClientId: '975477626776-u3lohpql1p806pvaladga283q97fgcgt.apps.googleusercontent.com',
    iosClientId: '975477626776-qebnik3egdc8d7oe8f8bpaein2gl82c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.activityTrackerApp',
  );
}
